theme = "blowfish"
title = "J2234's Log"
baseURL = "https://log.j2234.cc/"
languageCode = "ko-KR"


defaultContentLanguage = "ko"
ignoreFiles = ["_template"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[permalinks]
  posts = "/posts/:slug/"

[pagination]
  pagerSize = 6


[params]
  images = ["og-main.webp"]