theme = "blowfish"
baseURL = "https://log.j2234.cc/"
defaultContentLanguage = "en"
ignoreFiles = ["_template"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"