disabled = false
languageCode = "en"
languageName = "English"
weight = 1
contentDir = "content"
title = "J2234's log"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Backend, cloud, and problem-solving notes by j2234."
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "J2234"
  headline = "This is a simple space for my logs"
  bio = "Code, thoughts, and whatever."
  links = [
    { github = "https://github.com/jiheon2234" },
    { rss = "/index.xml" },
  ]
